routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\TaxonList;
/*
 * This file is part of the OpenDataBio app.
 * (c) OpenDataBio development team https://github.com/opendatabio
 */

// Landing page
Route::get('/', 'WelcomeController@index');

// Setting the locale:
Route::get('welcome/{locale}', 'WelcomeController@setAppLocale');
Route::get('home/{locale}', 'HomeController@setAppLocale');
// Home controller for logged in users
Route::get('/home', 'HomeController@index')->name('home');

// Default auth routes (login, logout, change password, etc)
Auth::routes();





Route::group(['middleware' => 'auth'], function() {
  
  // Users can update their own data
  Route::get('/token', 'Auth\SelfEditController@token');
  Route::post('/token', 'Auth\SelfEditController@resetToken');
  Route::get('/selfedit', 'Auth\SelfEditController@selfedit')->name('selfedit');
  Route::put('/selfupdate', 'Auth\SelfEditController@selfupdate')->name('selfupdate');

  /* IMPORT ROUTES */
  Route::post('import-locations', 'LocationController@importJob');
  Route::post('import-individuals', 'IndividualController@importJob');
  Route::post('import-individuallocations', 'IndividualController@importLocationsJob');
  Route::post('import-taxons', 'TaxonController@importJob');
  Route::post('import-vouchers', 'VoucherController@importJob');
  Route::post('import-traits', 'TraitController@importJob');
  Route::post('import-measurements', 'MeasurementController@importJob');
  Route::post('import-persons', 'PersonController@importJob');
  Route::post('import-biocollections', 'BiocollectionController@importJob');
  Route::get('import/{model}',function($model) {
    return view('common.import',compact('model'));
  });

  Route::get('individuals/identification-block','IndividualController@identificationBlock')->name('identificationblock');
  Route::post('activity/batch_delete', 'ActivityController@batchDelete');

  Route::get('persons/autocomplete', 'PersonController@autocomplete');
  Route::post('persons/batch_delete', 'PersonController@batchDelete');
  
  Route::post('userjobs/{userjob}/retry', 'UserJobController@retry');
  Route::post('userjobs/{userjob}/cancel', 'UserJobController@cancel');
  Route::post('userjobs/purge', 'UserJobController@purgeall');
  Route::get('userjobs-list', 'UserJobController@index')->name('userjobs.list');
  Route::resource('userjobs', 'UserJobController', ['only' => ['index', 'show', 'destroy']]);

  Route::get('references/autocomplete', 'BibReferenceController@autocomplete');

  Route::post('biocollections/checkih', 'BiocollectionController@checkih')->name('checkih');
  Route::get('biocollections/autocomplete','BiocollectionController@autocomplete');

  Route::post('odbrequests/{id}/annotate', 'RequestController@annotate');
  Route::get('odbrequests/{id}/biocollection', 'RequestController@indexBioCollection');
  Route::get('odbrequests/{id}/user', 'RequestController@indexUser');
  Route::post('odbrequests/individuals', 'RequestController@individualsRequest');
  Route::resource('odbrequests', 'RequestController',['only' => ['index', 'show', 'destroy']]);
  
  Route::get('dataset-version-create/{dataset_id}','\App\Http\Livewire\DatasetVersioning')->name('dataset.version.create');
  Route::get('dataset-version-edit/{dataset_version}','\App\Http\Livewire\DatasetVersioning')->name('dataset.version.edit');
  Route::get('trait-form/{odbtrait?}','\App\Http\Livewire\ODBTraitForm')->name('trait.form');
  Route::get('trait-unit-form/{trait_unit?}','\App\Http\Livewire\TraitUnitForm')->name('trait_unit.form');
  Route::get('measurement-form/{measurement?}','\App\Http\Livewire\MeasurementForm')->name('measurement.form');
  Route::get('measurement-form-object/{measured_id}/{measured_type}','\App\Http\Livewire\MeasurementForm')->name('measurement.form.object');


  Route::post('locations/individual_location', 'LocationController@saveForIndividual')->name('saveForIndividual');
  Route::post('locations/batch_delete', 'LocationController@batchDelete');

  Route::post('taxons/batch_delete', 'TaxonController@batchDelete');



Route::post('individuals/location-save', 'IndividualController@saveIndividualLocation')->name('saveIndividualLocation');
Route::post('references/findbibtexfromdoi', 'BibReferenceController@findBibtexFromDoi')->name('findbibtexfromdoi');
Route::get('individuals/location-delete', 'IndividualController@deleteIndividualLocation')->name('deleteIndividualLocation');
Route::post('individuals/batch_delete', 'IndividualController@batchDelete');
Route::post('individuals/batchidentify', 'IndividualController@batchidentifications');
Route::get('individuals/{id}/location/create', 'IndividualController@createLocations');
Route::get('individuals/create', 'IndividualController@create');
Route::post('odbrequest', 'RequestController@userRequest');
Route::get('vouchers/{id}/biocollection/create', 'VoucherController@createBioCollections');
Route::get('individuals/{id}/vouchers/create', 'VoucherController@createIndividuals');
Route::post('vouchers/batch_delete', 'VoucherController@batchDelete');
Route::get('traits/getformelement', 'TraitController@getFormElement');
Route::post('traits/batch_delete', 'TraitController@batchDelete');
Route::get('individuals/{id}/measurements/create', 'MeasurementController@createIndividuals');
Route::get('locations/{id}/measurements/create', 'MeasurementController@createLocations');
Route::get('taxons/{id}/measurements/create', 'MeasurementController@createTaxons');
Route::get('vouchers/{id}/measurements/create', 'MeasurementController@createVouchers');
Route::post('measurements/batch_delete', 'MeasurementController@batchDelete');



//PICTURES
//Batch upload pictures_files
Route::get('media/import-form', 'MediaController@uploadForm');
Route::post('import/media', 'MediaController@uploadSubmit');


Route::get('taxons/{id}/media-create', 'MediaController@createTaxons');
Route::get('locations/{id}/media-create', 'MediaController@createLocations');
Route::get('individuals/{id}/media-create','MediaController@createIndividuals');
Route::get('persons/{id}/media-create', 'MediaController@createMedia');
Route::get('traits/{id}/media-create', 'MediaController@createMedia');
Route::get('traits-categories/{id}/media-create', 'MediaController@createCategoryMedia');
Route::get('vouchers/{id}/media-create', 'MediaController@createVouchers');


/*
Route::get('forms/{id}/prepare', 'FormController@prepare');
Route::post('forms/{id}/fill', 'FormController@fill');
*/
Route::resource('forms', 'FormController',['only' => ['index']]);
Route::get('forms-edit/{form_id?}','\App\Http\Livewire\FormsEdit')->name('forms.edit');
Route::get('forms-show/{form_id}','\App\Http\Livewire\FormsShow')->name('forms.show');
Route::get('forms-fill/{form_id}','\App\Http\Livewire\FormsFill')->name('forms.fill');
Route::get('form-task-create/{form_id}','\App\Http\Livewire\FormTaskEdit')->name('form_tasks.create');
Route::get('form-task-edit/{form_task_id}','\App\Http\Livewire\FormTaskEdit')->name('form_tasks.edit');
Route::get('form-task/{form_task_id}','\App\Http\Livewire\FormTaskShow')->name('form_tasks.show');
Route::post('forms/batch_delete', 'FormController@batchDelete');
Route::get('forms-fill-task/{form_task_id}','\App\Http\Livewire\FormsFill')->name('forms.fill.task');


Route::post('exportdata', 'ExportController@exportData');
Route::get('individuals-identify','\App\Http\Livewire\IndividualsBatchIdentify')->name('individual.batchidentify');
Route::get('media-upload','\App\Http\Livewire\MediaUpload')->name('media.upload');


Route::get('individuals-job/{job_id}', 'IndividualController@indexUserJob')->name('individuals.index.userjob');
Route::get('vouchers-job/{job_id}', 'VoucherController@indexUserJob')->name('vouchers.index.userjob');
Route::get('traits-job/{job_id}', 'TraitController@indexUserJob')->name('traits.index.userjob');
Route::get('measurements-job/{job_id}', 'MeasurementController@indexUserJob')->name('measurements.index.userjob');
Route::get('persons-job/{job_id}', 'PersonController@indexUserJob')->name('persons.index.userjob');
Route::get('references-job/{job_id}', 'BibReferenceController@indexUserJob')->name('references.index.userjob');
Route::get('biocollections-job/{job_id}', 'BiocollectionController@indexUserJob')->name('biocollections.index.userjob');
Route::get('taxons-job/{job_id}', 'TaxonController@indexUserJob')->name('taxons.index.userjob');
Route::get('locations-job/{job_id}', 'LocationController@indexUserJob')->name('locations.index.userjob');



});



// Resources (with non-default BEFORE resources):
Route::get('persons/{id}/history', 'PersonController@activity');
Route::resource('persons', 'PersonController');


Route::get('references/{id}/history', 'BibReferenceController@activity');
Route::get('references/{id}/biocollection', 'BibReferenceController@indexBioCollection');
Route::resource('references', 'BibReferenceController');

Route::resource('biocollections', 'BiocollectionController');


Route::get('locations/{id}/location', 'LocationController@indexLocations');
Route::get('locations/{id}/activity', 'LocationController@activity');
Route::get('locations/{id}/project', 'LocationController@indexProjects');
Route::get('locations/{id}/dataset', 'LocationController@indexDatasets');
Route::get('locations/autocomplete', 'LocationController@autocomplete');
Route::get('locations/{id}/mapme', 'LocationController@mapMe');
Route::get('locations/{id}/mapspecies', 'LocationController@mapLocationSpecies');

Route::get('locations/autocomplete-related', 'LocationController@autocomplete_related');
Route::post('locations/autodetect', 'LocationController@autodetect')->name('autodetect');
//Route::post('locations/maprender', 'LocationController@maprender')->name('maprender');
Route::post('locations/map', 'LocationController@mapLocations');
Route::post('locations/custom-map', 'LocationController@mapCustom');
Route::resource('locations', 'LocationController');

app/Models/Person.php
<?php

/*
 * This file is part of the OpenDataBio app.
 * (c) OpenDataBio development team https://github.com/opendatabio
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use FuzzyWuzzy\Fuzz;
use Illuminate\Database\Eloquent\Builder;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

use CodeInc\StripAccents\StripAccents;
use Auth;

class Person extends Model
{

    use LogsActivity;
    //protected $revisionCreationsEnabled = true;

    // Gramatically incorrect, but helps development
    protected $table = 'persons';

    protected $fillable = ['full_name', 'abbreviation', 'email', 'email_public', 'institution', 'biocollection_id','notes'];

    //activity log
    //protected static $logName = 'person';
    protected static $recordEvents = ['updated','deleted'];
    //protected static $ignoreChangedAttributes = ['updated_at'];
    //protected static $logFillable = true;
    //protected static $logOnlyDirty = true;
    //protected static $submitEmptyLogs = false;
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
        ->useLogName('person')
        ->logFillable()
        ->logOnlyDirty()
        ->dontLogIfAttributesChangedOnly(['updated_at'])
        ->dontSubmitEmptyLogs();      
    }


    public function rawLink()
    {
        return "<a href='".url('persons/'.$this->id)."'>".htmlspecialchars($this->abbreviation).'</a>';
    }

    protected static function boot()
    {
        parent::boot();
        //static::bootRevisionableTrait();
        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('abbreviation', 'asc');
        });
        // before delete() method call this
        static::deleting(function($person) {
            /* if it has been assigned as a specialist */
            $person->taxons()->detach();
            // do the rest of the cleanup...
        });
    }

    // For use in Person::duplicates
    public static function normalize($text)
    {
        $text = trim(mb_strtolower($text));
        $text = preg_replace('/[^a-z ]/', '', $text);
        $tarr = explode(' ', $text);
        foreach ($tarr as $key => $token) {
            if (strlen($token) < 2) {
                unset($tarr[$key]);
            }
        }

        return join(' ', $tarr);
    }


    public function getNormalizedAbbreviationAttribute()
    {
      $normalized_abbreviation = trim(mb_strtoupper($this->abbreviation));
      $normalized_abbreviation = StripAccents::strip( (string) $normalized_abbreviation);
      $normalized_abbreviation = preg_replace('/[^a-zA-Z0-9]/', '', $normalized_abbreviation);
      return $normalized_abbreviation;
    }

    public function getFormatedNotesAttribute()
    {
      return ODBFunctions::formatNotes($this->notes);
    }
    public function getDtformatedNotesAttribute()
    {
      return ODBFunctions::formatNotes($this->notes,$title=false,'person-notes-'.$this->id);
    }

    public function getEmailAddressAttribute()
    {
      $valid = (null != Auth::user()) ? Auth::user()->access_level>=1 : false;
      if ($this->email_public or $valid) {
        return $this->email;
      }
      return null;
    }

    // Looks for possible duplication of persons. Returns a collection of possible dupes
    // perhaps instead of such complicated test, just compare the first letters of each word
    public static function duplicates($fullname, $abbreviation)
    {
        $fuzz = new Fuzz();
        $fullname = self::normalize($fullname);
        $abbreviation = self::normalize($abbreviation);
        $persons = self::all()->filter(function ($element) use ($fuzz, $fullname, $abbreviation) {
            $fn = self::normalize($element->full_name);
            $abb = self::normalize($element->abbreviation);
            $score = 0;
            $fchar = mb_strtolower(substr($element->full_name,0,1));
            $fchar2 = mb_strtolower(substr($fullname,0,1));

            return ($fuzz->weightedRatio($abb, $abbreviation) > 70 or
                   $fuzz->weightedRatio($fn, $fullname) > 70) and $fchar==$fchar2;
        })->sortBy('full_name');

        return $persons;
    }

    public function biocollection()
    {
        return $this->belongsTo(Biocollection::class);
    }

    // for specialist taxons
    public function taxons()
    {
        return $this->belongsToMany(Taxon::class);
    }

    public function taxonsAsAuthor()
    {
        return $this->hasMany(Taxon::class, 'author_id','id');
    }

    public function identifications()
    {
        return $this->hasMany(Identification::class,'person_id','id');
    }

    public function collected()
    {
        return $this->hasMany(Collector::class);
    }

    public function vouchers()
    {
        return $this->hasMany(Voucher::class);
    }

    public function measurements()
    {
        return $this->hasMany(Measurements::class);
    }

    // convenience alias
    public function getFullnameAttribute()
    {
        return $this->attributes['full_name'];
    }

    //for activity log
    public function identifiableName()
    {
        return $this->abbreviation;
    }
}

app/Models/TraitUnit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Lang;

class TraitUnit extends Model
{
    use Translatable;

    protected $table = 'trait_units';

    protected $fillable = ['unit']; 
       
    public function odbtraits()
    {
        return $this->hasMany(ODBTrait::class,'trait_unit_id');
    }

    public function getDisplayUnitAttribute()
    {
        return $this->unit." - ".$this->name;
    }

}

resources/views/traits/index.blade.php
@extends('layouts.app')

@section('content')
<div id='contents' class="container">
  <br>
  <div class="col-md-12 offset-md-0">
      <div class="card">
          <div class="card-header">
              @lang('messages.traits')
              @if(isset($object))
                @lang('messages.for'):&nbsp;<strong>@lang('messages.unit') 
                &nbsp;{{ $object->unit }}&nbsp;-&nbsp;{{ $object->name }}
                </strong>
              @else 
                &nbsp;&nbsp;      
                <a data-bs-toggle="collapse" href="#help" class="odb-unstyle"><i class="far fa-question-circle"></i></a>
                <div id="help" class="odb-hint collapse">
                  @lang('messages.traits_hint')
                </div>
              @endif
          </div>
          @if (Auth::user())
            {!! View::make('common.exportdata')->with([
                  'object' => isset($object) ? $object : null,
                  'export_what' => 'trait',
                  'filters' => isset($job_id) ? ['job_id'=> $job_id] : null,
            ]) !!}
          @else
            <br>
          @endif
          @if (Auth::user())
          <!--- delete form -->
          {!! View::make('common.batchdelete')->with([
                'url' => url('traits/batch_delete'),
          ]) !!}
          <br>
          @endif
          <div class="card-body">
          {!! $dataTable->table([],true) !!}
          </div>
      </div>
</div>
</div>

@endsection
@push ('scripts')
@push('scripts')
    {{ $dataTable->scripts(attributes: ['type' => 'module']) }}

    <script type="module">
    $(document).ready(function() {
    const table = $('#dataTableBuilder');
    table.on('preXhr.dt',function(e,settings,data) {
      data.type = $("#trait_type option").filter(':selected').val();
      /* an any defined in the export form */
      //data.project = $("input[name='project']").val();
      //data.location = $("input[name='location_root']").val();
      //data.taxon = $("input[name='taxon_root']").val();
      /*console.log(data.level,data.project,data.location,data.taxon); */
    });
    $('#trait_type').on('change',function() {
       table.DataTable().ajax.reload();
       return false;
    });
  });
</script>
@vite('resources/assets/js/custom.js')

@endpush

resources/views/traits/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
      <br>
      <div class="card col-lg-8 offset-lg-2 col-md-6 offset-md-3">
            <div class="card-header">
              @lang('messages.trait')
              &nbsp;
              <em>{{ $odbtrait->export_name }}</em>
              @if(Auth::user())
                    <span class="history" style="float:right">
                    <a class="history" href="{{url('traits/'.$odbtrait->id.'/activity')}}">
                      @lang ('messages.see_history')
                      </a>
                    </span>
                    @endif
          </div>
		<div class="card-body">
      <dl class="">
        <dt class="dt-odb">
@lang('messages.name')
</dt>
<dd class="mb-3">
{{ $odbtrait->name }}
</dd>
<dt class="dt-odb">
@lang('messages.id')
</dt>
<dd class="mb-3">
{{ $odbtrait->id }}
</dd>
<dt class="dt-odb">
@lang('messages.description')
</dt>
<dd class="mb-3">
{{ $odbtrait->description }}
</dd>
<dt class="dt-odb">
@lang('messages.type')
</dt>
<dd class="mb-3">
@lang ('levels.traittype.' . $odbtrait->type)
</dd>
<dt class="dt-odb">
@lang('messages.export_name')
</dt>
<dd class="mb-3">
{{ $odbtrait->export_name }}
</dd>

@if ($odbtrait->object_types)
<dt class="dt-odb">
    @lang('messages.object_types')
  </dt>
  <dd class="mb-3">
<ul>
@foreach ($odbtrait->object_types as $obtype)
    <li>{{ $obtype->name }}</li>
@endforeach
</ul>
</dd>

@endif

@if ($odbtrait->bibreferences->count())
<dt class="dt-odb">
@lang('messages.bibreference')
</dt>
<dd class="mb-3">
  {!! $odbtrait->bibreference_links !!}
</dd>
@endif

@if ($odbtrait->tags->count())
<dt class="dt-odb">
  @lang('messages.tagged_with')
</dt>
<dd class="mb-3">
  {!! $odbtrait->tag_links !!}
</dd>
@endif


@if ($odbtrait->parent_id)
<dt class="dt-odb">
@lang('messages.parent_trait')
</dt>
<dd class="mb-3">
{!! $odbtrait->parentTrait->rawLink() !!}
</dd>
@endif

@if ($odbtrait->dependentTraits()->count())
<dt class='dt-odb'>
@lang('messages.dependent_traits')
</dt>
<dd class='mb-3'>
  @foreach($odbtrait->dependentTraits as $dp)
    &nbsp;&nbsp;- {!! $dp->rawLink() !!} <br>
  @endforeach
</dd>
@endif

@if ( in_array( $odbtrait->type, [\App\Models\ODBTrait::QUANT_INTEGER, \App\Models\ODBTrait::QUANT_REAL]))
    @if ($odbtrait->trait_unit_id)
    <dt class="dt-odb">
    @lang('messages.unit')
  </dt>
  <dd class="mb-3">
    {{ $odbtrait->trait_unit->display_unit }}
  </dd>
    @endif
    @if ($odbtrait->range_min or $odbtrait->range_max)
    <dt class="dt-odb">
    @lang('messages.range')
  </dt>
  <dd class="mb-3">

    {!! $odbtrait->rangeDisplay !!}
  </dd>
    @endif
@endif

@if ( in_array( $odbtrait->type, [\App\Models\ODBTrait::SPECTRAL]))
    @if ($odbtrait->range_min or $odbtrait->range_max or $odbtrait->value_length)
    <dt class="dt-odb">
    @lang('messages.wavenumber_start') cm<sup>-1</sup>
  </dt>
  <dd class="mb-3">
    {{ $odbtrait->range_min }}
  </dd>
    <dt class="dt-odb">
    @lang('messages.wavenumber_end') cm<sup>-1</sup>
  </dt>
  <dd class="mb-3">

    {{ $odbtrait->range_max }}
  </dd>
    <dt class="dt-odb">
    @lang('messages.wavenumber_step')
  </dt>
  <dd class="mb-3">
    {{ $odbtrait->value_length }}
  </dd>
    @endif
@endif

@if ( in_array( $odbtrait->type, [\App\Models\ODBTrait::CATEGORICAL, \App\Models\ODBTrait::CATEGORICAL_MULTIPLE, \App\Models\ODBTrait::ORDINAL]) and $odbtrait->categories)
<dt class="dt-odb">@lang('messages.categories')</dt>
<dd class="mb-4">
<table class="table table-striped" style='font-size: 0.9em;'> <thead>
  @if ($odbtrait->type == \App\Models\ODBTrait::ORDINAL)
      <th>@lang('messages.rank')</th>
  @else
      <th></th>
  @endif
 <th>
   @lang('messages.name')
  </th>
  <th>
   @lang('messages.description')
  </th>
</thead>
<tbody>
@foreach ($odbtrait->categories as $cat)
<tr>
    <td> {{$cat->rank}}</td>
    <td> {{$cat->name}}</td>
    <td> {{$cat->description}}</td>
</tr>
@endforeach
</tbody>
</table>
</dd>
@endif

@if ($odbtrait->type == \App\Models\ODBTrait::LINK)
<dt class="dt-odb">
@lang('messages.link_type')
</dt>
<dd class="mb-3">
@lang('classes.' . $odbtrait->link_type)
</dd>
@endif

<div class='mt-3 mb-5'>
@if ($odbtrait->notes)
  {!! $odbtrait->formated_notes !!}
@endif
</div>

</dl>

<div class="row g-3 p-2" id='odb-delete-confirmation-form' style="display: none;">
  <p class="col-auto alert alert-danger">
    @lang('messages.action_not_undone')
  </p>
  <form class='col-auto' action="{{ url('traits/'. $odbtrait->id)  }}" method="POST" >
    {{ csrf_field() }}
    {{ method_field('DELETE') }}
    <button type="submit" class="btn btn-danger mt-3" title="@lang('messages.remove')">
      <i class="far fa-trash-alt"></i>
      @lang('messages.remove')
    </button>
  </form>
</div>

<div class='row g-3' >
  @can ('update', $odbtrait)
  			    <div class="col-auto px-2">
  				<a href="{{ route('trait.form',[
            'odbtrait' => $odbtrait->id,
            ] )}}" class="btn btn-success" name="submit" value="submit">
  @lang('messages.edit')
  				</a>
  			    </div>
  @endcan

  @can ('delete', $odbtrait)
  <div class="col-auto px-2">
    <button class="odb-delete-confirmation-button btn btn-danger" type='button' >
      @lang('messages.remove')
    </button>
  </div>
  @endcan

  <div class="col-auto px-2">
    <a href="{{ url('measurements/'. $odbtrait->id. '/trait')  }}" class="btn btn-outline-secondary" name="submit" value="submit">
      <i class="fa fa-btn fa-search"></i>
      @lang('messages.measurements')
    </a>
</div>




</div>
                </div>
            </div>
    </div>
@endsection

@once
  @push ('scripts')
  @vite('resources/assets/js/custom.js')
  @endpush
@endonce