routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\TaxonList;
/*
 * This file is part of the OpenDataBio app.
 * (c) OpenDataBio development team https://github.com/opendatabio
 */

// Landing page
Route::get('/', 'WelcomeController@index');

// Setting the locale:
Route::get('welcome/{locale}', 'WelcomeController@setAppLocale');
Route::get('home/{locale}', 'HomeController@setAppLocale');
// Home controller for logged in users
Route::get('/home', 'HomeController@index')->name('home');

// Default auth routes (login, logout, change password, etc)
Auth::routes();





Route::group(['middleware' => 'auth'], function() {
  
  // Users can update their own data
  Route::get('/token', 'Auth\SelfEditController@token');
  Route::post('/token', 'Auth\SelfEditController@resetToken');
  Route::get('/selfedit', 'Auth\SelfEditController@selfedit')->name('selfedit');
  Route::put('/selfupdate', 'Auth\SelfEditController@selfupdate')->name('selfupdate');

  /* IMPORT ROUTES */
  Route::post('import-locations', 'LocationController@importJob');
  Route::post('import-individuals', 'IndividualController@importJob');
  Route::post('import-individuallocations', 'IndividualController@importLocationsJob');
  Route::post('import-taxons', 'TaxonController@importJob');
  Route::post('import-vouchers', 'VoucherController@importJob');
  Route::post('import-traits', 'TraitController@importJob');
  Route::post('import-measurements', 'MeasurementController@importJob');
  Route::post('import-persons', 'PersonController@importJob');
  Route::post('import-biocollections', 'BiocollectionController@importJob');
  Route::get('import/{model}',function($model) {
    return view('common.import',compact('model'));
  });

  Route::get('individuals/identification-block','IndividualController@identificationBlock')->name('identificationblock');
  Route::post('activity/batch_delete', 'ActivityController@batchDelete');

  Route::get('persons/autocomplete', 'PersonController@autocomplete');
  Route::post('persons/batch_delete', 'PersonController@batchDelete');
  
  Route::post('userjobs/{userjob}/retry', 'UserJobController@retry');
  Route::post('userjobs/{userjob}/cancel', 'UserJobController@cancel');
  Route::post('userjobs/purge', 'UserJobController@purgeall');
  Route::get('userjobs-list', 'UserJobController@index')->name('userjobs.list');
  Route::resource('userjobs', 'UserJobController', ['only' => ['index', 'show', 'destroy']]);

  Route::get('references/autocomplete', 'BibReferenceController@autocomplete');

  Route::post('biocollections/checkih', 'BiocollectionController@checkih')->name('checkih');
  Route::get('biocollections/autocomplete','BiocollectionController@autocomplete');

  Route::post('odbrequests/{id}/annotate', 'RequestController@annotate');
  Route::get('odbrequests/{id}/biocollection', 'RequestController@indexBioCollection');
  Route::get('odbrequests/{id}/user', 'RequestController@indexUser');
  Route::post('odbrequests/individuals', 'RequestController@individualsRequest');
  Route::resource('odbrequests', 'RequestController',['only' => ['index', 'show', 'destroy']]);
  
  Route::get('dataset-version-create/{dataset_id}','\App\Http\Livewire\DatasetVersioning')->name('dataset.version.create');
  Route::get('dataset-version-edit/{dataset_version}','\App\Http\Livewire\DatasetVersioning')->name('dataset.version.edit');
  Route::get('trait-form/{odbtrait?}','\App\Http\Livewire\ODBTraitForm')->name('trait.form');
  Route::get('trait-unit-form/{trait_unit?}','\App\Http\Livewire\TraitUnitForm')->name('trait_unit.form');
  Route::get('measurement-form/{measurement?}','\App\Http\Livewire\MeasurementForm')->name('measurement.form');
  Route::get('measurement-form-object/{measured_id}/{measured_type}','\App\Http\Livewire\MeasurementForm')->name('measurement.form.object');


  Route::post('locations/individual_location', 'LocationController@saveForIndividual')->name('saveForIndividual');
  Route::post('locations/batch_delete', 'LocationController@batchDelete');

  Route::post('taxons/batch_delete', 'TaxonController@batchDelete');



Route::post('individuals/location-save', 'IndividualController@saveIndividualLocation')->name('saveIndividualLocation');
Route::post('references/findbibtexfromdoi', 'BibReferenceController@findBibtexFromDoi')->name('findbibtexfromdoi');
Route::get('individuals/location-delete', 'IndividualController@deleteIndividualLocation')->name('deleteIndividualLocation');
Route::post('individuals/batch_delete', 'IndividualController@batchDelete');
Route::post('individuals/batchidentify', 'IndividualController@batchidentifications');
Route::get('individuals/{id}/location/create', 'IndividualController@createLocations');
Route::get('individuals/create', 'IndividualController@create');
Route::post('odbrequest', 'RequestController@userRequest');
Route::get('vouchers/{id}/biocollection/create', 'VoucherController@createBioCollections');
Route::get('individuals/{id}/vouchers/create', 'VoucherController@createIndividuals');
Route::post('vouchers/batch_delete', 'VoucherController@batchDelete');
Route::get('traits/getformelement', 'TraitController@getFormElement');
Route::post('traits/batch_delete', 'TraitController@batchDelete');
Route::get('individuals/{id}/measurements/create', 'MeasurementController@createIndividuals');
Route::get('locations/{id}/measurements/create', 'MeasurementController@createLocations');
Route::get('taxons/{id}/measurements/create', 'MeasurementController@createTaxons');
Route::get('vouchers/{id}/measurements/create', 'MeasurementController@createVouchers');
Route::post('measurements/batch_delete', 'MeasurementController@batchDelete');



//PICTURES
//Batch upload pictures_files
Route::get('media/import-form', 'MediaController@uploadForm');
Route::post('import/media', 'MediaController@uploadSubmit');


Route::get('taxons/{id}/media-create', 'MediaController@createTaxons');
Route::get('locations/{id}/media-create', 'MediaController@createLocations');
Route::get('individuals/{id}/media-create','MediaController@createIndividuals');
Route::get('persons/{id}/media-create', 'MediaController@createMedia');
Route::get('traits/{id}/media-create', 'MediaController@createMedia');
Route::get('traits-categories/{id}/media-create', 'MediaController@createCategoryMedia');
Route::get('vouchers/{id}/media-create', 'MediaController@createVouchers');


/*
Route::get('forms/{id}/prepare', 'FormController@prepare');
Route::post('forms/{id}/fill', 'FormController@fill');
*/
Route::resource('forms', 'FormController',['only' => ['index']]);
Route::get('forms-edit/{form_id?}','\App\Http\Livewire\FormsEdit')->name('forms.edit');
Route::get('forms-show/{form_id}','\App\Http\Livewire\FormsShow')->name('forms.show');
Route::get('forms-fill/{form_id}','\App\Http\Livewire\FormsFill')->name('forms.fill');
Route::get('form-task-create/{form_id}','\App\Http\Livewire\FormTaskEdit')->name('form_tasks.create');
Route::get('form-task-edit/{form_task_id}','\App\Http\Livewire\FormTaskEdit')->name('form_tasks.edit');
Route::get('form-task/{form_task_id}','\App\Http\Livewire\FormTaskShow')->name('form_tasks.show');
Route::post('forms/batch_delete', 'FormController@batchDelete');
Route::get('forms-fill-task/{form_task_id}','\App\Http\Livewire\FormsFill')->name('forms.fill.task');


Route::post('exportdata', 'ExportController@exportData');
Route::get('individuals-identify','\App\Http\Livewire\IndividualsBatchIdentify')->name('individual.batchidentify');
Route::get('media-upload','\App\Http\Livewire\MediaUpload')->name('media.upload');


Route::get('individuals-job/{job_id}', 'IndividualController@indexUserJob')->name('individuals.index.userjob');
Route::get('vouchers-job/{job_id}', 'VoucherController@indexUserJob')->name('vouchers.index.userjob');
Route::get('traits-job/{job_id}', 'TraitController@indexUserJob')->name('traits.index.userjob');
Route::get('measurements-job/{job_id}', 'MeasurementController@indexUserJob')->name('measurements.index.userjob');
Route::get('persons-job/{job_id}', 'PersonController@indexUserJob')->name('persons.index.userjob');
Route::get('references-job/{job_id}', 'BibReferenceController@indexUserJob')->name('references.index.userjob');
Route::get('biocollections-job/{job_id}', 'BiocollectionController@indexUserJob')->name('biocollections.index.userjob');
Route::get('taxons-job/{job_id}', 'TaxonController@indexUserJob')->name('taxons.index.userjob');
Route::get('locations-job/{job_id}', 'LocationController@indexUserJob')->name('locations.index.userjob');



});



// Resources (with non-default BEFORE resources):
Route::get('persons/{id}/history', 'PersonController@activity');
Route::resource('persons', 'PersonController');


Route::get('references/{id}/history', 'BibReferenceController@activity');
Route::get('references/{id}/biocollection', 'BibReferenceController@indexBioCollection');
Route::resource('references', 'BibReferenceController');

Route::resource('biocollections', 'BiocollectionController');


Route::get('locations/{id}/location', 'LocationController@indexLocations');
Route::get('locations/{id}/activity', 'LocationController@activity');
Route::get('locations/{id}/project', 'LocationController@indexProjects');
Route::get('locations/{id}/dataset', 'LocationController@indexDatasets');
Route::get('locations/autocomplete', 'LocationController@autocomplete');
Route::get('locations/{id}/mapme', 'LocationController@mapMe');
Route::get('locations/{id}/mapspecies', 'LocationController@mapLocationSpecies');

Route::get('locations/autocomplete-related', 'LocationController@autocomplete_related');
Route::post('locations/autodetect', 'LocationController@autodetect')->name('autodetect');
//Route::post('locations/maprender', 'LocationController@maprender')->name('maprender');
Route::post('locations/map', 'LocationController@mapLocations');
Route::post('locations/custom-map', 'LocationController@mapCustom');
Route::resource('locations', 'LocationController');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <br>
  <div class="col-lg-10 offset-lg-1 col-md-6 offset-md-3 mb-5">
      <div class="card">
        <div class="card-header">
          <h4>@lang ('customs.landing_page_welcome')</h4>
        </div>
        <div class="card-body">
          <div class="col-sm-12">
          <p>@lang('messages.welcome_summary',compact('nindividuals', 'nvouchers','ndatasets','nprojects','nmeasurements'))</p>
        </div>
        <dl>

        <dt class='dt-odb'>@lang ('messages.your_default_person')</dt>
        @if (Auth::user()->person)
          <dd>{!! Auth::user()->person->rawLink() !!}</dd>
        @else
          <dd class='text-danger'>@lang ('messages.no_default_person')</dd>
        @endif
        <dt class="dt-odb">
          @lang('messages.api_token')
        </dt>
        <dd>
          <span class="large"> {{ Auth::user()->api_token }} </span>
        </dd>

          <dt class='dt-odb'>@lang ('messages.default_project')</dt>
        @if (Auth::user()->defaultProject)
          <dd>{!! Auth::user()->defaultProject->rawLink() !!}</dd>
        @else
          <dd class='text-danger'>@lang('messages.no_default_project')</dd>
        @endif
          <dt class='dt-odb'>@lang ('messages.default_dataset')</dt>
        @if (Auth::user()->defaultDataset)
          <dd>{!! Auth::user()->defaultDataset->rawLink() !!}</dd>
          @else
            <dd class='text-danger'>@lang('messages.no_default_dataset')</dd>
        @endif
        </dl>
        <br>

        <!-- BUTTONS -->
        <nav class="navbar navbar-light navbar-expand-lg">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarbuttons" aria-controls="navbarbuttons" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarbuttons">
              <br>
              <ul class="navbar-nav mb-lg-0 g-3">
                <li class="nav-item px-2 mb-2">
                  <a href="{{ route('selfedit') }}" class="btn btn-success">
                    @lang('messages.edit_profile')
                  </a>
                </li>

                @if (Auth::user()->projects()->count())
                <li class="nav-item px-2 mb-2">
            <a data-bs-toggle="collapse" href="#myprojects" class="btn btn-outline-secondary">@lang('messages.my_projects')</a>
          </li>
          @endif

          @if (Auth::user()->datasets()->count())
            <li class="nav-item px-2 mb-2">
            <a data-bs-toggle="collapse" href="#mydatasets" class="btn btn-outline-secondary">@lang('messages.my_datasets')</a>
          </li>
          @endif

          @if (Auth::user()->forms()->count())
            <li class="nav-item px-2 mb-2">
            <a data-bs-toggle="collapse" href="#myforms" class="btn btn-outline-secondary">@lang('messages.forms')</a>
            </li>
          @endif

          @if(Auth::user())
            <li class="nav-item px-2 mb-2">
              <a href="{{ url('token') }}" class="btn btn-outline-secondary">
                @lang('messages.api_token')
              </a>
            </li>

            <li class="nav-item px-2 mb-2">
            <a href="{{ route('userjobs.index') }}" class="btn btn-outline-secondary">
              @lang('messages.userjobs')</a>
            </li>

          <li class="nav-item px-2 mb-2">
            <a href="{{ url('odbrequests/'. Auth::user()->id. '/user')  }}" class="btn btn-outline-secondary" name="submit" value="submit">
              <i class="fa fa-btn fa-search"></i>
              @lang('messages.request_user')
            </a>
          </li>
          @endif
        </ul>
      </div>
    </div>
  </nav>
    </div>

    <div class="card collapse" id='myprojects'>
      @if (Auth::user()->projects()->count())
        <div class="card-header">
          @lang('messages.my_projects')
        </div>
        <div class="card-body">
            <ul>
              @foreach (Auth::user()->projects as $project)
                <li>{!! $project->rawLink() !!} (@lang('levels.project.' . $project->pivot->access_level ))</li>
              @endforeach
            </ul>
        </div>
      @endif
    </div>

    <div class="card collapse" id='mydatasets'>
      @if (Auth::user()->datasets()->count())
      <div class="card-header">
        @lang('messages.datasets')
      </div>
      <div class="card-body">
        <ul>
          @foreach (Auth::user()->datasets as $dataset)
            <li>{!! $dataset->rawLink() !!}  (@lang('levels.project.' . $dataset->pivot->access_level ))</li>
          @endforeach
        </ul>
      </div>
      @endif
    </div>
    <div class="card collapse" id='myforms'>
      @if (Auth::user()->forms()->count())
      <div class="card-header">
        @lang('messages.forms')
      </div>
      <div class="card-body">
          <ul>
            @foreach (Auth::user()->forms as $form)
              <li>{!! $form->rawLink() !!}</li>
            @endforeach
          </ul>
      </div>
      @endif
    </div>
    </div>
</div>
</div>

@endsection